import appliancesImg from '../../assets/gb-shop/images/main/appliances.png';
import appleLogo from '../../assets/gb-shop/icons/apple.svg';
import lithuania from '../../assets/gb-shop/icons/lithuania.svg';

export const appliances = [
  {
    id: 1,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 2,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 3,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 4,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 5,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 6,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 7,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 8,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 9,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 10,
    name: 'Мясорубка Avinas AV-081',
    image: appliancesImg,
    storeName: 'Техно мир',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
];
