import garmentsImg from '../../assets/gb-shop/images/main/garments.png';
import appleLogo from '../../assets/gb-shop/icons/apple.svg';
import lithuania from '../../assets/gb-shop/icons/lithuania.svg';

export const garments = [
  {
    id: 1,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 2,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 3,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 4,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 5,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 6,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 7,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 8,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 9,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 10,
    name: 'Зимние толстовки',
    image: garmentsImg,
    storeName: 'Apple',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
];
