import shoesImg from '../../assets/gb-shop/images/main/shoes.png';
import appleLogo from '../../assets/gb-shop/icons/apple.svg';
import lithuania from '../../assets/gb-shop/icons/lithuania.svg';

export const shoes = [
  {
    id: 1,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 2,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 3,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 4,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 5,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 6,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 7,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 8,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 9,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
  {
    id: 10,
    name: 'Adidas (X, XL, 2XL)',
    image: shoesImg,
    storeName: 'Adidas',
    storeLogo: appleLogo,
    countryFlag: lithuania,
  },
];
