export const parcel = [
  {
    id: 1,
    number: '№122233445',
    sender: 'Компания 1',
    deliveryDate: '22 июнь 2023',
    reciever: 'Компания 2',
    status: 'в пути',
    country: 'Кыргызстан',
    city: 'Бишкек',
  },
  {
    id: 2,
    number: '№45452343445',
    sender: 'Компания 3',
    deliveryDate: '21 июль 2023',
    reciever: 'Компания 4',
    status: 'в пути',
    country: 'Россия',
    city: 'Москва',
  },
  {
    id: 3,
    number: '№122453445',
    sender: 'Компания 5',
    deliveryDate: '10 июль 2023',
    reciever: 'Компания 6',
    status: 'в пути',
    country: 'Казахстан',
    city: 'Астана',
  },
  {
    id: 4,
    number: '№1234343445',
    sender: 'Компания 7',
    deliveryDate: '09 март 2023',
    reciever: 'Компания 8',
    status: 'в пути',
    country: 'Кыргызстан',
    city: 'Бишкек',
  },
  {
    id: 5,
    number: '№1226576445',
    sender: 'Компания 9',
    deliveryDate: '29 апрель 2023',
    reciever: 'Компания 10',
    status: 'в пути',
    country: 'Кыргызстан',
    city: 'Бишкек',
  },
  {
    id: 6,
    number: '№1223433435',
    sender: 'Компания 11',
    deliveryDate: '13 май 2023',
    reciever: 'Компания 12',
    status: 'в пути',
    country: 'Кыргызстан',
    city: 'Бишкек',
  },
];
